version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    image: ehrs-backend:latest
    environment:
      JWT_SECRET: hellolitteuser
      PORT: 4000
      PRISMA_PORT: 5555
      PROCESS_PREFIX: prod
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
    ports:
      - "4000:4000"
      - "5555:5555"
    restart: always
    depends_on:
      - postgres
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: ehrs-frontend:latest
    environment:
      # TODO: Replace the ip with the host name
      VITE_API_URL: http://localhost:4000
      VITE_PREVIEW_PORT: 8050
      PORT: 5173
      HOST: 0.0.0.0
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - backend
    networks:
      - mynetwork
  
  curl:
    image: alpine/curl
    command: sleep 100000
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge

