export const medicalCampId = 2;

export const addressOptions = [
  { label: 'Gachibowli', value: 'Gachibowli' },
  { label: 'Borabanda', value: 'Borabanda' },
  { label: 'Siddiq Nagar', value: 'Siddiq Nagar' },
  { label: 'Anjaiah nagar', value: 'Anjaiah nagar' },
  { label: 'Raidurg Dabha', value: 'Raidurg Dabha' },
  { label: 'kajaguda', value: 'kajaguda' },
  { label: 'DLF', value: 'DLF' },
  { label: 'Darga', value: 'Darga' },
  { label: 'Diamond Hills', value: 'Diamond Hills' },
  { label: 'Rajiv Nagar', value: 'Rajiv Nagar' },
  { label: 'Narsingi', value: 'Narsingi' },
  { label: 'Basavatarak nagar', value: 'Basavatarak nagar' },
  { label: 'Lambadi basthi', value: 'Lambadi basthi' },
  { label: 'Greenland Colony', value: 'Greenland Colony' },
  { label: 'Kokapet', value: 'Kokapet' },
  { label: 'Masidbanda', value: 'Masidbanda' },
  { label: 'Nanakramguda', value: 'Nanakramguda' },
  { label: 'Gandipet', value: 'Gandipet' },
  { label: 'vaddera basthi', value: 'vaddera basthi' },
  { label: 'Adarsha colony', value: 'Adarsha colony' },
  { label: 'Balajinagar', value: 'Balajinagar' },
  { label: 'Gowlidoddi', value: 'Gowlidoddi' },
  { label: 'Keshavanagar', value: 'Keshavanagar' },
  { label: 'Labour Colony', value: 'Labour Colony' },
  { label: 'Bapunagar', value: 'Bapunagar' },
  { label: 'journalist colony', value: 'journalist colony' },
  { label: 'NTR Nagar', value: 'NTR Nagar' },
  { label: 'Ameenpur', value: 'Ameenpur' },
  { label: 'Chandanagar', value: 'Chandanagar' },
  { label: 'AshokNagar', value: 'AshokNagar' },
  { label: 'Lingampally', value: 'Lingampally' },
  { label: 'Beeramguda', value: 'Beeramguda' },
  { label: 'bhel', value: 'bhel' },
  { label: 'My Home Colony', value: 'My Home Colony' },
  { label: 'Hafizpet', value: 'Hafizpet' },
  { label: 'HYDERGUDA', value: 'HYDERGUDA' },
  { label: 'BDL', value: 'BDL' },
  { label: 'Patancheru', value: 'Patancheru' },
  { label: 'Baghlingampally', value: 'Baghlingampally' },
  { label: 'Abids', value: 'Abids' },
  { label: 'Kachiguda', value: 'Kachiguda' },
  { label: 'Gandhi Nagar', value: 'Gandhi Nagar' },
  { label: 'Himayathnagar', value: 'Himayathnagar' },
  { label: 'Begumpet', value: 'Begumpet' },
  { label: 'Bowenpally', value: 'Bowenpally' },
  { label: 'A.S.Rao Nagar', value: 'A.S.Rao Nagar' },
  { label: 'Tarnaka', value: 'Tarnaka' },
  { label: 'Lalapet', value: 'Lalapet' },
  { label: 'MALKAZGIRI', value: 'MALKAZGIRI' },
  { label: 'Balanagar', value: 'Balanagar' },
  { label: 'Bachupally', value: 'Bachupally' },
  { label: 'Pragathinagar', value: 'Pragathinagar' },
  { label: 'kphb colony', value: 'kphb colony' },
  { label: 'Brindavan Colony', value: 'Brindavan Colony' },
  { label: 'Gajularamaram', value: 'Gajularamaram' },
  { label: 'Jagathgirigutta', value: 'Jagathgirigutta' },
  { label: 'Film nagar', value: 'Film nagar' },
  { label: 'Chithrapuri Colony', value: 'Chithrapuri Colony' },
  { label: 'Erragadda', value: 'Erragadda' },
  { label: 'Krishna Nagar', value: 'Krishna Nagar' },
  { label: 'M L Nagar', value: 'M L Nagar' },
  { label: 'Kanamet', value: 'Kanamet' },
  { label: 'Janardhan hills', value: 'Janardhan hills' },
  { label: 'Kondapur', value: 'Kondapur' },
  { label: 'Kothaguda', value: 'Kothaguda' },
  { label: 'Madhapur', value: 'Madhapur' },
  { label: 'Meenakshi Deliot', value: 'Meenakshi Deliot' },
  { label: 'Bandlaguda', value: 'Bandlaguda' },
  { label: 'Jiyaguda', value: 'Jiyaguda' },
  { label: 'Aramghar', value: 'Aramghar' },
  { label: 'Chandrayanagutta', value: 'Chandrayanagutta' },
  { label: 'Attapur', value: 'Attapur' },
  { label: 'Langar house', value: 'Langar house' },
  { label: 'Kushaiguda', value: 'Kushaiguda' },
  { label: 'Bibinagar', value: 'Bibinagar' },
  { label: 'Gatkesar', value: 'Gatkesar' },
  { label: 'ecil', value: 'ecil' },
  { label: 'Gudimalkapur', value: 'Gudimalkapur' },
  { label: 'Ibrahimpatnam', value: 'Ibrahimpatnam' },
  { label: 'Miyapur', value: 'Miyapur' },
  { label: 'Rtc X Roads', value: 'Rtc X Roads' },
  { label: 'Secundarabad', value: 'Secundarabad' },
  { label: 'Kukatpally', value: 'Kukatpally' },
  { label: 'Ameerpet', value: 'Ameerpet' },
  { label: 'Hitech city', value: 'Hitech city' },
  { label: 'Old city', value: 'Old city' },
  { label: 'LB Nagar', value: 'LB Nagar' },
  { label: 'Nellore', value: 'Nellore' },
  { label: 'Cheerala', value: 'Cheerala' },
  { label: 'Miryalaguda', value: 'Miryalaguda' },
  { label: 'Siddipet', value: 'Siddipet' },
  { label: 'Nalagonda', value: 'Nalagonda' },
  { label: 'Sircilla', value: 'Sircilla' },
  { label: 'vikarabad', value: 'vikarabad' },
  { label: 'korutla', value: 'korutla' },
  { label: 'gajwal', value: 'gajwal' },
  { label: 'Thandor', value: 'Thandor' },
  { label: 'manugur', value: 'manugur' },
  { label: 'Mahaboob Nagar', value: 'Mahaboob Nagar' },
  { label: 'Khammam', value: 'Khammam' },
  { label: 'bhadrachalam', value: 'bhadrachalam' },
  { label: 'Budvel', value: 'Budvel' },
  { label: 'Bodhan', value: 'Bodhan' },
  { label: 'Mallepally', value: 'Mallepally' },
  { label: 'Medak', value: 'Medak' },
  { label: 'Armmor', value: 'Armmor' },
  { label: 'Jahirabad', value: 'Jahirabad' },
  { label: 'Suryapet', value: 'Suryapet' },
  { label: 'Raichur', value: 'Raichur' },
];
